DROP DATABASE IF EXISTS BookSellerDB;
CREATE DATABASE BookSellerDB;
USE BookSellerDB;

CREATE TABLE Books(
    ISBN INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Title VARCHAR(40),
    PubDate DATETIME, 
    Format VARCHAR(30),
    Price FLOAT
); 

CREATE TABLE Authors(
    AuthorID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(100),
    LastName VARCHAR(100)
);

CREATE TABLE Books_By_Author(
    AuthorID INT NOT NULL,
    ISBN INT NOT NULL ,
    FOREIGN KEY(AuthorID) REFERENCES Authors(AuthorID),
    FOREIGN KEY(ISBN) REFERENCES Books(ISBN)
);

CREATE TABLE Customers(
    CustomerID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(100),
    LastName VARCHAR(100),
    EMail VARCHAR(50),
    Phone VARCHAR(80)
);